import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'screens/welcome/welcome_screen.dart';
import 'screens/auth/login_screen.dart';

void main() {
  runApp(const TingaTalkApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
// Updated to match your exact theme expectations
class TingaTalkApp extends StatelessWidget {
  const TingaTalkApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Set system UI overlay style for dark theme
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.light,
        systemNavigationBarColor: Color.fromARGB(255, 18, 32, 47),
        systemNavigationBarIconBrightness: Brightness.light,
      ),
    );

    return MaterialApp(
      title: 'TingaTalk',
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
        primaryColor: const Color(0xFFB111AA),
        colorScheme: const ColorScheme.dark(
          primary: Color(0xFFB111AA),
          secondary: Color(0xFFC084FC),
          surface: Color.fromARGB(255, 18, 32, 47),
        ),
      ),
      home: const WelcomeScreen(),
      routes: {
        '/welcome': (context) => const WelcomeScreen(),
        '/login': (context) => const LoginScreen(),
      },
      debugShowCheckedModeBanner: false,
    );
  }
}

